### ISSUE TITLE
osgjs plugin

### ISSUE THREAD

**Issue by Imp-Tech** [openscenegraph/osg#31]
Hello!
I can export from osg to osgjs fromat with osgjs plugin. Please tell me:i can load from osgjs to osg format?

**Comment by jtorresfabra** [comment]
No, you can't.

**Comment by AquilesCanta** [comment]
Hi @jtorresfabra, apologies for the spam. Are there any plans for supporting osgjs to osg conversions? Would you be willing to accept contributions on this topic? Or if you can point me to a better place to ask, that'd be great as well. Thanks!

**Comment by jtorresfabra** [comment]
> Hi @jtorresfabra, apologies for the spam. Are there any plans for supporting osgjs to osg conversions?
Not that I'm aware. 
> Would you be willing to accept contributions on this topic?
I'm not the one accepting or rejecting submissions, said that it would be a nice addition.

**Comment by mp3butcher** [comment]
I don't think it's not in OSG roadmap to get online so there's no community interest to read osgjs files
Further osg aims OpenGL when osgjs aims WebGL so the requirements are not quite the same (WebGL resources management for ex)
see that with osgjs maintainers perhaps they can fill wholes of osgjs with default osg stuff in order to output osgt file... it's easier to treat txt with js than create a C++99 js parser.

**Comment by jtorresfabra** [comment]
Hi @mp3butcher, just a couple of comments (disclaimer, I'm also a maintainer of the osgjs library):

> I don't think it's not in OSG roadmap to get online so there's no community interest to read osgjs files

It's surprising that you know what is the roadmap and what is the community interest, as we are probably more than 10k developers working daily with OSG. Reading osgjs files is something that has been asked several times, both in the osgjs list and here, so actually there could be a bit of interest.
Also there is community member on going to work to port OSG to wasm (with some nice results by the way), so maybe going web is something that people like to see. 
Also from what I've read from Robert sometimes he would like to decouple plugins from the core, but it seems that is not gonna happen in the short term.

Anyway if you have some information than the rest of us don't, please, don't hesitate to share :).  

> see that with osgjs maintainers perhaps they can fill wholes of osgjs with default osg stuff in order to output osgt file... it's easier treating json with js than creating a C++99 json parser.

well, he actually asked to one osgjs maintainer (in fact 2 because he also asked in the osgjs github). But probably this is the wrong place -a closed issue-. Writting osgt from osgjs, or just writting a Reader for the osgjs Writer is definitely not in our roadmap, I know for sure. But it may help to others and we would be happy to help revieweing or whatever. 

> (Personnaly I've already made a json parser for the purpose of IBLloading and i used some C0 feature so it can't be part of osg)

Maybe coding with C99/03 is not the best, but it can be done, there are even plugins in OSG working with the boost library. 

Cheers.
